# Generated by Django 3.2.2 on 2021-05-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0001_initialize_basic_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
