# Generated by Django 3.2.2 on 2021-05-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class _SensorTypeEnum(models.TextChoices):
    MOISTURE = "MOISTURE"
    TEMPERATURE = "TEMPERATURE"
    LIGHT = "LIGHT"


def upgrade(apps, schema_editor):
    Device = apps.get_model("sensors", "Device")
    SensorType = apps.get_model("sensors", "SensorType")
    db_alias = schema_editor.connection.alias
    Device.objects.using(db_alias).create(name="RPI")
    SensorType.objects.using(db_alias).bulk_create(
        [
            SensorType(name=_SensorTypeEnum.MOISTURE.value),
            SensorType(name=_SensorTypeEnum.TEMPERATURE.value),
            SensorType(name=_SensorTypeEnum.LIGHT.value),
        ]
    )


def downgrade(apps, schema_editor):
    Device = apps.get_model("sensors", "Device")
    SensorType = apps.get_model("sensors", "SensorType")
    db_alias = schema_editor.connection.alias
    Device.objects.using(db_alias).filter(name="RPI").delete()
    SensorType.objects.using(db_alias).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0001_initialize_basic_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(choices=[("RPI", "Raspberry Pi")], max_length=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("add_date", models.DateTimeField(auto_now_add=True)),
                ("state", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sensors.device"
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plants.plant",
                    ),
                ),
                (
                    "sensor_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sensors.sensortype",
                    ),
                ),
            ],
        ),
        migrations.RunPython(upgrade, downgrade),
    ]
