# Generated by Django 3.2.2 on 2021-05-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_add_mac_address_to_the_device_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('parameters', models.CharField(blank=True, max_length=511, null=True)),
                ('sensor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.sensor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cli',
            constraint=models.UniqueConstraint(fields=('module', 'name', 'sensor'), name='UQ_cli__module__name__sensor_id'),
        ),
        migrations.AddConstraint(
            model_name='cli',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='UQ_cli__module__name'),
        ),
    ]
