"""Add description and image to the plant model

Revision ID: 0246c18280bc
Revises: 63a76765edfd
Create Date: 2021-04-18 13:27:07.489526+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0246c18280bc"
down_revision = "63a76765edfd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Plant", sa.Column("Description", sa.Unicode(length=512), nullable=True))
    op.add_column("Plant", sa.Column("Image", sa.Unicode(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Plant", "Image")
    op.drop_column("Plant", "Description")
    # ### end Alembic commands ###
