"""Change uniqueness of name and PlantId-SensorTypeId pair of sensor

Revision ID: 02b595558fdd
Revises: 0246c18280bc
Create Date: 2021-05-02 18:55:22.560606+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "02b595558fdd"
down_revision = "0246c18280bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Sensor", sa.Column("Description", sa.Unicode(length=255), nullable=True))
    op.create_unique_constraint("UQ__SensorTypeId__PlantId", "Sensor", ["PlantId", "SensorTypeId"])
    op.drop_constraint("UQ__Sensor__Name", "Sensor", type_="unique")
    op.drop_column("Sensor", "Name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Sensor", sa.Column("Name", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint("UQ__Sensor__Name", "Sensor", ["Name"])
    op.drop_constraint("UQ__SensorTypeId__PlantId", "Sensor", type_="unique")
    op.drop_column("Sensor", "Description")
    # ### end Alembic commands ###
